model: runs/classify/train15/weights/best.pt
data: dataset_mix_ft_clean4
epochs: 100
imgsz: 320
batch: 80
workers: 4
seed: 42
device: 0
patience: 30

fliplr: 0.0
flipud: 0.0
auto_augment: randaugment
erasing: 0.2
hsv_h: 0.02
hsv_s: 0.8
hsv_v: 0.5
scale: 0.6
lr0: 0.001
# yolo classify train cfg=train_mix.yaml
