model: runs/classify/train29/weights/best.pt
data: dataset_fatigue_face_mix_ft_v2
epochs: 6
imgsz: 224
batch: 32
workers: 2
seed: 42
device: 0

optimizer: AdamW
lr0: 0.00005
lrf: 1.0
warmup_epochs: 0.0
weight_decay: 0.0005
patience: 2

fliplr: 0.0
flipud: 0.0
auto_augment: null
erasing: 0.0
hsv_h: 0.0
hsv_s: 0.2
hsv_v: 0.2
scale: 0.2


#yolo classify train cfg=train_face_4.yaml
